package ventanas;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import libroBD.conexion;
import funciones.LibroBL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class libros extends javax.swing.JPanel {
    int idGlobal=0;
    //ConectarBD objConexion = new ConectarBD();

    DefaultTableModel modelo;
    /**
     * Creates new form Panel1
     */
    public libros() {
        initComponents();
        
        String[]titulos={"Titulo","Link"};
        modelo=new DefaultTableModel(null,titulos);
        tblLIBRO.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtLink = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLIBRO = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Link");
        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblLIBRO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLIBRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLIBROMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLIBRO);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEditar)
                        .addGap(10, 53, 53)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(10, 20,68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.limpiar();
    }                                           

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        try {
        ConectarBD objConexion = new ConectarBD();
        LibroBL oLIBRO=recuperarDatosGUI();
        String atrSentenciaInsert = String.format("DELETE FROM LIBRO WHERE titulo='%s'",oLIBRO.getTitulo());
        
        objConexion.ejecutarSentenciaSQL(atrSentenciaInsert);
        
        this.mostrarDatos();        
        limpiar();
        objConexion.con.close();
        }catch (Exception e){

        }
    }                                         

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                           

        try {
        ConectarBD objConexion = new ConectarBD();
        LibroBL oLIBRO=recuperarDatosGUI();
        String atrSentenciaInsert = String.format("INSERT INTO LIBRO (COD_LIBRO, TITULO, LINK_LIBRO, DOCENTE_COD_DOCENTE)"
                + " VALUES (null, '%s', '%s', 1)",oLIBRO.getTitulo(),oLIBRO.getLink());
        
        objConexion.ejecutarSentenciaSQL(atrSentenciaInsert);
        this.mostrarDatos();
        limpiar();
        objConexion.con.close();

        }catch(Exception e){}
        
    }                                          

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          

        try {
        ConectarBD objConexion = new ConectarBD();
        LibroBL oLIBRO=recuperarDatosGUI();
        String atrSentenciaInsert = String.format("UPDATE LIBRO SET TITULO='%s',"
                + "LINK_LIBRO='%s' WHERE COD_LIBRO="+idGlobal+"",oLIBRO.getTitulo(),oLIBRO.getLink());
        
        objConexion.ejecutarSentenciaSQL(atrSentenciaInsert);
        this.mostrarDatos();
        limpiar();
        }catch(Exception e){}
    }                                         

    private void tblLIBROMouseClicked(java.awt.event.MouseEvent evt) {                                       
               if(evt.getClickCount()==1){
        
            JTable receptor= (JTable)evt.getSource();
            txtTitulo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            txtLink.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            LibroBL oLIBRO=recuperarDatosGUI();
            String tituloE=oLIBRO.getTitulo();
            idGlobal=encontrarID(tituloE);
            
            btnAgregar.setEnabled(false);
            btnEditar.setEnabled(true);
            btnBorrar.setEnabled(true);
            
        }
    }                                      

    public void mostrarDatos(){
        
        while(modelo.getRowCount()>0){
        
            modelo.removeRow(0);
        }

        try {
            ConectarBD objConexion = new ConectarBD();
        ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM LIBRO");
        
        while(resultado.next()){
        
            System.out.println(resultado.getString("COD_LIBRO"));
            System.out.println(resultado.getString("TITULO"));
            System.out.println(resultado.getString("LINK_LIBRO"));
            
            Object[] oUsuario={resultado.getString("TITULO"),resultado.getString("LINK_LIBRO")};
            modelo.addRow(oUsuario);
        }

        objConexion.con.close();
        } catch(SQLException e){
            System.out.println(e);
        }
        
       }
    public int encontrarID(String nombre){
    
        int res=0;

        try {
            ConectarBD objConexion = new ConectarBD();
                 ResultSet resultado=objConexion.consultarRegistro("SELECT COD_LIBRO FROM LIBRO WHERE titulo='"+nombre+"'");
        
        while(resultado.next()){
        
            System.out.println("Id encontrado" + resultado.getString("COD_LIBRO"));
            res=parseInt(resultado.getString("COD_LIBRO"));
            System.out.println("Id convertido" + res);
        }
        objConexion.con.close();
        } catch(SQLException e){
            System.out.println(e);
        }
        
        return res;
    }
    
    
    public LibroBL recuperarDatosGUI(){
        LibroBL oLIBRO=new LibroBL();
        
        oLIBRO.setTitulo(txtTitulo.getText());
        oLIBRO.setLink(txtLink.getText());
    return oLIBRO;
    }
    
    public void limpiar(){
    
        txtTitulo.setText("");
        txtLink.setText("");
        ///Desabilitamos botones
       
        btnAgregar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnBorrar.setEnabled(false);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLIBRO;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration                   
}
